### PR TITLE
Make sure all_dependents variable is being used as a set

### PR DESCRIPTION
**Pull request by Ladsgroup**
Bug: T206333

### CODE REVIEW

**Comment by mariushoch** [comment]
I have an alternative up at #423 where I switched these from using the bitwise `&` to `and`.

**Comment by Ladsgroup** [comment]
I'm not sure it would work. Generally speaking, and is different from & between sets. E.g. 
```
self.revision = set(123)
all_dependents = set(234)
```
Will give true for "and" and give false for &. I don't know exact values of these variables to judge fully though so I went with conservative approach.

**Comment by halfak** [comment]
I'm confused.  It seem that `all_dependents` is turned into a list at https://github.com/wikimedia/revscoring/blob/e46c3fcbeeba9a348aa3e9b0fb7098e10dc70a23/revscoring/extractors/api/extractor.py#L97

Then in this version of the code, we regularly convert it back to a set in order to perform set operations.  Why not just leave it as a set and convert it to a list when a list is needed?  E.g. https://github.com/wikimedia/revscoring/blob/e46c3fcbeeba9a348aa3e9b0fb7098e10dc70a23/revscoring/extractors/api/extractor.py#L219

**Comment by Ladsgroup** [comment]
Hmm, that sounds okay to me. Made #429

**Comment by halfak** [comment]
@Ladsgroup please delete if you're done with this.

**Pull request closed without merging**
