### PR TITLE
Adds wikitext.revision.list_items as a feature

### PR DESCRIPTION
**Pull request by halfak**
https://phabricator.wikimedia.org/T223782

### CODE REVIEW

**Comment by Sharingan-Coder01** [comment]
I took a look at this as we discussed, this looks great and should be good enough to merge.

**Comment by halfak** [comment]
@elukey or @kevinbazira, can you or someone on the team help get this review unblocked?

**Review by chrisalbon — APPROVED** [review]
lgtm

**Comment by chrisalbon** [comment]
@halfak My apologies for the long wait. We should have reviewed and approved this sooner. I'm going to change my alerts to make sure we see and review GitHub PR's faster.

**Comment by halfak** [comment]
Awesome!  Thank you!

**Pull request merged**
