### PR TITLE
Start of using mwbase instead of pywikibase in wikibase parts

### PR DESCRIPTION
**Pull request by Ladsgroup**
Sitelinks and things related to claims will be complex, let's start with this

Bug: T194758

### CODE REVIEW

**Comment by Ladsgroup** [comment]
https://github.com/mediawiki-utilities/python-mwbase/pull/2 will fix this breakage.

**Comment by Ladsgroup** [comment]
It still fails :/

**Comment by halfak** [comment]
Finally, this *should* be ready.

**Comment by Ladsgroup** [comment]
We need to make sure we rebuild our models (and adjust our features in editqaulity and itemquality) before deploying this to prod.

**Pull request merged**
