### PR TITLE
Revert CJK work and start version 2.10.0 

### PR DESCRIPTION
**Pull request by halfak**
We did a lot of work on CJK processing in 2.9.x.  Regretfully the functionality is not planned to be used in production right now, and the approach includes some tradeoffs (big libraries and asset downloads for CJK processing), so I think we should move it to a feature branch and continue work on 2.10.x minus the CJK stuff until we are ready.

Bug: https://phabricator.wikimedia.org/T287021

* This pull request removes the relevant CJK work.  See the revscoring-2.9 branch that preserves history at this point.  
* This pull request also increments the version to 2.10.0.  
* Note that some changes to `requirements.txt` and `CHANGELOG.md` are preserved as they represent minor bug fixes and real release history.

### CODE REVIEW

**Comment by elukey** [comment]
@halfak Hi! Can you add more info about this pull request? It is very big and without any description it is difficult to review..

**Comment by halfak** [comment]
Sorry.  Need some more work before it's ready for review.  I'll flag it as a draft in the meantime.  

The gist is that we did a lot of work on CJK processing in 2.9.x and I want to move that to a feature branch since the work has stopped, the functionality is not planned to be used in production right now, and the approach includes some tradeoffs (big libraries and asset downloads for CJK processing).  

Somehow I'm struggling with getting git to understand a wholesale revert without doing a reset (breaking master for everyone who was working since 2.8.2).  Once I have that settled, I'll move this out of draft and ping you for discussion (if that's alright).

**Comment by halfak** [comment]
OK it should be read for review.  For some reason, I don't see the travis run.  It seems like maybe some permissions were taken away from me for this repo?

**Comment by elukey** [comment]
Hey Aaron, the only thing that we changed is documented in https://phabricator.wikimedia.org/T281711 and it is basically to allow us (as ML team) to review all the changes and organize the path to deployment in production (rather than leaving things accumulating etc..). I don't see any Travis run either, so I don't believe it is something related to permission, I'll try to follow up next week :)

**Comment by elukey** [comment]
Aaron is there a task related to this patch? I am wondering what path-to-production it should follow, just to organize future deployments/reviews/etc..

**Comment by halfak** [comment]
I just added a task.  See https://phabricator.wikimedia.org/T287021

Re. path to production, revscoring 2.8.2 and 2.10.0 should be 100% compatible so there's no production changes that need to be made immediately, but there have been some bug fixes in dependent that affect how we generate features related to cited and uncited content that I'd like to incorporate.  That will involve rebuilding the article quality models for English and Dutch Wikipedia because they rely on those features.  We'll likely see some (probably minor) fitness improvements.

**Review by accraze — APPROVED** [review]
LGTM :eyes: :+1:

**Pull request merged**
