### PR TITLE
cjk update

### PR DESCRIPTION
**Pull request by 5uperpalo**

### CODE REVIEW

**Comment by 5uperpalo** [comment]
@halfak  please check the current version of the code, I believe I finally found a way how to get the CJK tokenization into revscoring. I wanted to give up - as there was always some kind of error related to super() in Revision classes, but it was stuck in my head and now it seems that it is finally working. I believe it had something to do with this:
https://www.reddit.com/r/learnpython/comments/ckszou/python_crash_course_inheritance_typeerror_object/
and maybe polymorphims? - I am still a bit confused how it worked before when there are multiple "class Revision"s

**Comment by 5uperpalo** [comment]
as discussed I added the documentation of cjk tokenized features

**Comment by 5uperpalo** [comment]
notes on how I fixed the issuesthat came up after running the tests related to cjk tokenization in revscoring mentioned by Aaron here:
https://gist.github.com/halfak/38ff73b5e3cde579a0c41f0d46b98f6a

[notes_to_revscoring_tests.txt](https://github.com/wikimedia/revscoring/files/5570020/notes_to_revscoring_tests.txt)

**Comment by halfak** [comment]
Excellent work.  Thanks for working through the details.

**Pull request merged**
