### PR TITLE
Fixed 3 failed tests produced by pull request #512

### PR DESCRIPTION
**Pull request by Sahethi**
On testing the changes made in the PR #512 

There were 3 failed tests that needed to be fixed
image

I have fixed the 3 tests, please review it
image

### CODE REVIEW

**Comment by halfak** [comment]
@sharingan-coder01 or @nikhil-11, can you review?

**Comment by Sahethi** [comment]
Hey! @halfak I just wanted to know if the PR can be reviewed?

**Comment by Sahethi** [comment]
Hey! @halfak 
Just wanted to reiterate, can you please review this PR?

**Comment by elukey** [comment]
The change works in my local environment! 

@Sharingan-Coder01 and @nikhil-11 Hi! If you have time and if you are still interested in the project, do you mind to review the pull request?

**Comment by elukey** [comment]
@Sahethi Hi! Thanks a lot for the pull request, sorry for the lag. The pull request looks good, but after a chat with a colleague I am wondering if we could avoid the term "Hijra" (since IIUC it is a word in Hindi often used in derogatory terms). The idea would be to avoid saving to a public repository a word that may offend other community members working on it. Would it be a problem to update the pull request? Thanks in advance!

**Comment by Sahethi** [comment]
> @Sahethi Hi! Thanks a lot for the pull request, sorry for the lag. The pull request looks good, but after a chat with a colleague I am wondering if we could avoid the term "Hijra" (since IIUC it is a word in Hindi often used in derogatory terms). The idea would be to avoid saving to a public repository a word that may offend other community members working on it. Would it be a problem to update the pull request? Thanks in advance!

Hey @elukey 
Thanks for getting back. I will update the pull request.

**Comment by elukey** [comment]
@Sahethi thanks! Lemme know when I can re-check, happy to merge after your update :)

**Comment by Sahethi** [comment]
> @Sahethi thanks! Lemme know when I can re-check, happy to merge after your update :)

Hey! You can check the PR now, I made the changes in `revscoring/languages/hindi.py` and `tests/languages/test_hindi.py`.

**Review by elukey — APPROVED** [review]

**Comment by elukey** [comment]
Thanks a lot! Merged!

**Pull request merged**
